version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo "$(aws ecr get-login-password --region $AWS_DEFAULT_REGION) | docker login --username AWS --password-stdin $REPOSITORY_URI"
      - echo Checking Docker username...
      - docker info | grep Username

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t avo-backend:dev .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging the Docker image...
      - docker tag avo-backend:dev $REPOSITORY_URI:dev
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:dev